### ISSUE TITLE
Kickoff

### ISSUE THREAD

**Issue by bhack** [ctuning/ck-tiny-dnn#1]
How we can bootstrap here? Is it still too early to define a todo list?

**Comment by gfursin** [comment]
We are overwhelmed with our current projects at the moment and at the moment can't spare more time on anything else :( ... But I still do hope to get back to unified DNN benchmarking whenever we have more time or more man-power. That's why in the mean time, we announced a few internships related to DNN crowd-benchmarking and crowd-tuning based on CK:
* https://dividiti.blogspot.fr/2017/01/several-exciting-internships-about-dnn.html

**Comment by bhack** [comment]
I see that there are some little news in the repository /cc @edgarriba

**Comment by gfursin** [comment]
Ehhhhhhhhh, I considerably overestimated our current effort required to 
process
even Caffe (all the mess with numerous dependencies, changing 
interfaces, etc)
and we are obliged to finish that project before being able to look at 
other frameworks.

So sadly no spare resources and time at all at this stage :( - I am 
honestly very sad
and sorry about that :( ...

cc @psyhtest

**Comment by bhack** [comment]
Oh.. nevermind :smile: I was just surprised to already found activity here.
